// Code generated by goctl. DO NOT EDIT!
// Source: qyWxBinDing.proto

package server

import (
	"ZeroProject/Rpc/qyWxBinDing/internal/logic"
	"context"

	"ZeroProject/Rpc/qyWxBinDing/internal/svc"
	pb "ZeroProject/Rpc/qyWxBinDing/pb"
)

type QyWxBinDingServer struct {
	svcCtx *svc.ServiceContext
}

func (s *QyWxBinDingServer) QyUserId(ctx context.Context, request *pb.QyUserIdRequest) (*pb.QyUserIdResponse, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.QyUserId(request)
}

func (s *QyWxBinDingServer) QyBinDing(ctx context.Context, request *pb.Request) (*pb.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.ObtainQyWx(request)
}

func NewQyWxBinDingServer(svcCtx *svc.ServiceContext) *QyWxBinDingServer {
	return &QyWxBinDingServer{
		svcCtx: svcCtx,
	}
}
