// Code generated by goctl. DO NOT EDIT!
// Source: qyWxBinDing.proto

//go:generate mockgen -destination ./qywxbinding_mock.go -package qywxbindingclient -source $GOFILE

package qywxbindingclient

import (
	"context"

	pb "ZeroProject/Rpc/qyWxBinDing/pb"

	"github.com/tal-tech/go-zero/zrpc"
)

type (

	QyWxBinDing interface {
		QyBinDing(ctx context.Context, in *pb.Request) (*pb.Response, error)
		QyUserId(ctx context.Context, in *pb.QyUserIdRequest) (*pb.QyUserIdResponse, error)
	}

	defaultQyWxBinDing struct {
		cli zrpc.Client
	}
)

func (d defaultQyWxBinDing) QyUserId(ctx context.Context, in *pb.QyUserIdRequest) (*pb.QyUserIdResponse, error) {
	client := pb.NewQyWxBinDingClient(d.cli.Conn())
	return client.QyUserId(ctx, in)
}

func (d defaultQyWxBinDing) QyBinDing(ctx context.Context, in *pb.Request) (*pb.Response, error) {
	client := pb.NewQyWxBinDingClient(d.cli.Conn())
	return client.QyBinDing(ctx, in)
}

func NewQyWxBinDing(cli zrpc.Client) QyWxBinDing {
	return &defaultQyWxBinDing{
		cli: cli,
	}
}
