// Code generated by protoc-gen-go. DO NOT EDIT.
// source: qyWxBinDing.proto

package qyWxBinDing

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	ErpName              string   `protobuf:"bytes,1,opt,name=ErpName,proto3" json:"ErpName,omitempty"`
	Pwd                  string   `protobuf:"bytes,2,opt,name=Pwd,proto3" json:"Pwd,omitempty"`
	WxName               string   `protobuf:"bytes,3,opt,name=WxName,proto3" json:"WxName,omitempty"`
	Cron                 string   `protobuf:"bytes,4,opt,name=Cron,proto3" json:"Cron,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cf02a3fa7bbc301, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetErpName() string {
	if m != nil {
		return m.ErpName
	}
	return ""
}

func (m *Request) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

func (m *Request) GetWxName() string {
	if m != nil {
		return m.WxName
	}
	return ""
}

func (m *Request) GetCron() string {
	if m != nil {
		return m.Cron
	}
	return ""
}

type Response struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Number               string   `protobuf:"bytes,2,opt,name=Number,proto3" json:"Number,omitempty"`
	Code                 int64    `protobuf:"varint,3,opt,name=Code,proto3" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cf02a3fa7bbc301, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Response) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Response) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

type QyUserIdRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QyUserIdRequest) Reset()         { *m = QyUserIdRequest{} }
func (m *QyUserIdRequest) String() string { return proto.CompactTextString(m) }
func (*QyUserIdRequest) ProtoMessage()    {}
func (*QyUserIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cf02a3fa7bbc301, []int{2}
}

func (m *QyUserIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QyUserIdRequest.Unmarshal(m, b)
}
func (m *QyUserIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QyUserIdRequest.Marshal(b, m, deterministic)
}
func (m *QyUserIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QyUserIdRequest.Merge(m, src)
}
func (m *QyUserIdRequest) XXX_Size() int {
	return xxx_messageInfo_QyUserIdRequest.Size(m)
}
func (m *QyUserIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QyUserIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QyUserIdRequest proto.InternalMessageInfo

func (m *QyUserIdRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type QyUserIdResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	Expire               int64    `protobuf:"varint,2,opt,name=Expire,proto3" json:"Expire,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QyUserIdResponse) Reset()         { *m = QyUserIdResponse{} }
func (m *QyUserIdResponse) String() string { return proto.CompactTextString(m) }
func (*QyUserIdResponse) ProtoMessage()    {}
func (*QyUserIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cf02a3fa7bbc301, []int{3}
}

func (m *QyUserIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QyUserIdResponse.Unmarshal(m, b)
}
func (m *QyUserIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QyUserIdResponse.Marshal(b, m, deterministic)
}
func (m *QyUserIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QyUserIdResponse.Merge(m, src)
}
func (m *QyUserIdResponse) XXX_Size() int {
	return xxx_messageInfo_QyUserIdResponse.Size(m)
}
func (m *QyUserIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QyUserIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QyUserIdResponse proto.InternalMessageInfo

func (m *QyUserIdResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *QyUserIdResponse) GetExpire() int64 {
	if m != nil {
		return m.Expire
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "qyWxBinDing.Request")
	proto.RegisterType((*Response)(nil), "qyWxBinDing.Response")
	proto.RegisterType((*QyUserIdRequest)(nil), "qyWxBinDing.QyUserIdRequest")
	proto.RegisterType((*QyUserIdResponse)(nil), "qyWxBinDing.QyUserIdResponse")
}

func init() { proto.RegisterFile("qyWxBinDing.proto", fileDescriptor_8cf02a3fa7bbc301) }

var fileDescriptor_8cf02a3fa7bbc301 = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x89, 0xa9, 0x69, 0x3b, 0x3d, 0x58, 0x87, 0x5a, 0x42, 0x51, 0x90, 0x9c, 0xf4, 0xd2,
	0x83, 0x5e, 0x3c, 0x8a, 0x5a, 0xd4, 0x83, 0xc5, 0x2c, 0x4a, 0xcf, 0x2d, 0x19, 0x4a, 0x90, 0xee,
	0xa6, 0xbb, 0x2d, 0x26, 0xff, 0xc2, 0x9f, 0x2c, 0x99, 0xcc, 0xd2, 0x5a, 0xf0, 0xf6, 0xde, 0xcb,
	0xe3, 0xdb, 0x97, 0x5d, 0x38, 0x5d, 0x57, 0xb3, 0xf2, 0x21, 0xd7, 0x4f, 0xb9, 0x5e, 0x8e, 0x0b,
	0x6b, 0x36, 0x06, 0x7b, 0x7b, 0x51, 0x32, 0x87, 0xb6, 0xa2, 0xf5, 0x96, 0xdc, 0x06, 0x63, 0x68,
	0x4f, 0x6c, 0x31, 0x9d, 0xaf, 0x28, 0x0e, 0x2e, 0x83, 0xab, 0xae, 0xf2, 0x16, 0xfb, 0x10, 0xbe,
	0x7f, 0x67, 0xf1, 0x11, 0xa7, 0xb5, 0xc4, 0x21, 0x44, 0xb3, 0x92, 0xab, 0x21, 0x87, 0xe2, 0x10,
	0xa1, 0xf5, 0x68, 0x8d, 0x8e, 0x5b, 0x9c, 0xb2, 0x4e, 0x5e, 0xa0, 0xa3, 0xc8, 0x15, 0x46, 0x3b,
	0x26, 0xbd, 0xb9, 0xa5, 0xf0, 0x6b, 0x59, 0x93, 0xa6, 0xdb, 0xd5, 0x82, 0xac, 0xe0, 0xc5, 0x31,
	0xc9, 0x64, 0x0d, 0x3f, 0x54, 0xac, 0x93, 0x6b, 0x38, 0x49, 0xab, 0x4f, 0x47, 0xf6, 0x35, 0xf3,
	0xa3, 0x87, 0x10, 0x35, 0x81, 0x30, 0xc5, 0x25, 0xf7, 0xd0, 0xdf, 0x55, 0xe5, 0xf0, 0x01, 0x1c,
	0x7f, 0x98, 0x2f, 0xd2, 0x52, 0x6d, 0x4c, 0x4d, 0x98, 0x94, 0x45, 0x6e, 0x89, 0x07, 0x84, 0x4a,
	0xdc, 0xcd, 0x4f, 0x00, 0xbd, 0x74, 0x77, 0x53, 0x78, 0x07, 0xdd, 0xb4, 0xf2, 0x66, 0x30, 0xde,
	0xbf, 0x57, 0x19, 0x33, 0x3a, 0x3b, 0x48, 0xe5, 0xdc, 0x67, 0xe8, 0xf8, 0x2d, 0x78, 0xfe, 0xa7,
	0x72, 0xf0, 0x37, 0xa3, 0x8b, 0x7f, 0xbe, 0x36, 0xa0, 0x45, 0xc4, 0x0f, 0x78, 0xfb, 0x1b, 0x00,
	0x00, 0xff, 0xff, 0x1e, 0x0b, 0xc8, 0x16, 0xd5, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QyWxBinDingClient is the client API for QyWxBinDing service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QyWxBinDingClient interface {
	QyBinDing(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	QyUserId(ctx context.Context, in *QyUserIdRequest, opts ...grpc.CallOption) (*QyUserIdResponse, error)
}

type qyWxBinDingClient struct {
	cc *grpc.ClientConn
}

func NewQyWxBinDingClient(cc *grpc.ClientConn) QyWxBinDingClient {
	return &qyWxBinDingClient{cc}
}

func (c *qyWxBinDingClient) QyBinDing(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/qyWxBinDing.QyWxBinDing/QyBinDing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qyWxBinDingClient) QyUserId(ctx context.Context, in *QyUserIdRequest, opts ...grpc.CallOption) (*QyUserIdResponse, error) {
	out := new(QyUserIdResponse)
	err := c.cc.Invoke(ctx, "/qyWxBinDing.QyWxBinDing/QyUserId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QyWxBinDingServer is the server API for QyWxBinDing service.
type QyWxBinDingServer interface {
	QyBinDing(context.Context, *Request) (*Response, error)
	QyUserId(context.Context, *QyUserIdRequest) (*QyUserIdResponse, error)
}

// UnimplementedQyWxBinDingServer can be embedded to have forward compatible implementations.
type UnimplementedQyWxBinDingServer struct {
}

func (*UnimplementedQyWxBinDingServer) QyBinDing(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QyBinDing not implemented")
}
func (*UnimplementedQyWxBinDingServer) QyUserId(ctx context.Context, req *QyUserIdRequest) (*QyUserIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QyUserId not implemented")
}

func RegisterQyWxBinDingServer(s *grpc.Server, srv QyWxBinDingServer) {
	s.RegisterService(&_QyWxBinDing_serviceDesc, srv)
}

func _QyWxBinDing_QyBinDing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QyWxBinDingServer).QyBinDing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qyWxBinDing.QyWxBinDing/QyBinDing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QyWxBinDingServer).QyBinDing(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _QyWxBinDing_QyUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QyUserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QyWxBinDingServer).QyUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qyWxBinDing.QyWxBinDing/QyUserId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QyWxBinDingServer).QyUserId(ctx, req.(*QyUserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _QyWxBinDing_serviceDesc = grpc.ServiceDesc{
	ServiceName: "qyWxBinDing.QyWxBinDing",
	HandlerType: (*QyWxBinDingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QyBinDing",
			Handler:    _QyWxBinDing_QyBinDing_Handler,
		},
		{
			MethodName: "QyUserId",
			Handler:    _QyWxBinDing_QyUserId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "qyWxBinDing.proto",
}
