// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"ZeroProject/Api/unifiedLogin/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

/*
	路由
*/
func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login/unifiedLogin",
				Handler: UnifiedLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/to_ken/refresh",
				Handler: AuthTokenRefresh(serverCtx),
			},
		},
	)
}
