// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"ZeroProject/Api/authToken/internal/svc"
	"net/http"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/to_ken/dataByTime",
				Handler: authTokenTestHandler(serverCtx),
			},
			//{
			//	Method:  http.MethodGet,
			//	Path:    "/to_ken/refresh",
			//	Handler: authTokenRefresh(serverCtx),
			//},
		},
	)
}
