// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginReply struct {
	Expire      int64  `json:"expire,omitempty"`
	AccessToken string `json:"token,omitempty"`
	Msg         string `json:"msg,omitempty"`
}

type TokenResponse struct {
	Token  string `json:"token"`
	Expire int64  `json:"ExpiresAt"`
}