# 有多个nacos时，请用逗号分开，ip，port，NamespaceId，Name，RotateTime，LogLevel数量必须一致
Nacos:
  Ip: [ "10.28.83.123" ] # nacos IP
  Port: [ 8848 ] # nacos 端口
  NamespaceId: [ 99681f09-8811-46b4-a318-4d629c1e1da6 ] # nacos 命名ID
  Name: [ prod ] # 命名
  RotateTime: [ 1h ]
  LogLevel: [ debug ]
  # LogDir: [ ./nacos/server/log ]
  # CacheDir: [ ./nacos/server/cache ]

RegisterService:
  Prot: 8080
  # GroupName: ["1","1"]
  ClusterName: unifiedLogin
