// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Erpname  string `json:"Erpname"`  // Erp账号
	Password string `json:"password"` // 密码
	Wxname   string `json:"Wxname"`   // 微信账号
	//Cron     string `json:"cron"`     // cron 表达式
}

type Response struct {
	Message string `json:"msg"`
	Code    int64  `json:"code"`
}

type WebLicenseResponse struct {
	Code     int    `json:"Code,omitempty"`
	Location string `json:"Location,omitempty"`
	Msg      string `json:"msg,omitempty"`
}

type QyWxCodeRequest struct {
	Code string `json:"code"`
}

type QyWxCodeResponse struct {
	Data     string `json:"data,omitempty"`
	Location string `json:"Location,omitempty"`
	Msg      string `json:"msg,omitempty"`
}

type AuthSuCcRequest struct {
	UserId string `form:"userId,omitempty"`
}

type AuthSuCcResponse struct {
	Msg string `json:"msg,omitempty"`
}

type QyUserIdResponse struct {
	Token  string `json:"token,omitempty"`
	Expire int64  `json:"expire,omitempty"`
	Msg    string `json:"msg,omitempty"`
}
